### ISSUE TITLE
可以增加图像识别的功能吗

### ISSUE THREAD

**Issue by zhouliwang** [openatx/uiautomator2#247]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
Your code or log here
```

## Versions (版本)
通过`pip show uiautomator2`可以获取到

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
让组里的小弟在弄了




            
            
                
                    
                            
                                
                            
                            
                                命令行
                            
                    
                        
                            
                                    邮箱：codeskyblue@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年11月08日 08:30，zhouliwang 写道： 注，代码或者日志请使用Markdown语法，看完删掉
Your code or log here

Versions (版本)
通过pip show uiautomator2可以获取到
Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

手机型号?
错误日志?
出错的代码片段?

Screenshots （相关截图）
能有尽量有
Additional Details （其他信息）

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openatx/uiautomator2","title":"openatx/uiautomator2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/openatx/uiautomator2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"可以增加图像识别的功能吗 (#247)"}],"action":{"name":"View Issue","url":"https://github.com/openatx/uiautomator2/issues/247"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openatx/uiautomator2/issues/247",
"url": "https://github.com/openatx/uiautomator2/issues/247",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "可以增加图像识别的功能吗 (#247)",
"sections": [
{
"text": "",
"activityTitle": "**zhouliwang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@zhouliwang",
"facts": [
{
"name": "Repository: ",
"value": "openatx/uiautomator2"
},
{
"name": "Issue #: ",
"value": 247
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"openatx/uiautomator2\",\n\"issueId\": 247,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"openatx/uiautomator2\",\n\"issueId\": 247\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/openatx/uiautomator2/issues/247"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 407835729\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by flyfire100** [comment]
这个我目前用的腾讯的优图，免费的OCR，只是识别率有点低
