### ISSUE TITLE
USB disconnected, fallback to WiFi, ATX_AGENT_URL

### ISSUE THREAD

**Issue by JunGaJang** [openatx/uiautomator2#598]
- 手机型号：逍遥模拟器最新版
- uiautomator2的版本号：2.11.4
- 相关日志
`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.0.2.15', port=7912): Max retries exceeded with url: /services/uiautomator (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000278995B2E08>, 'Connection to 10.0.2.15 timed out. (connect timeout=3)'))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='10.0.2.15', port=7912): Max retries exceeded with url: /services/uiautomator (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000278995B2E08>, 'Connection to 10.0.2.15 timed out. (connect timeout=3)'))`
- 代码。
d = u2.connect_adb_wifi(serial)
-问题
我现在是windows电脑连接逍遥模拟器，但是偶尔超时，应该用什么方式调用比较好，异常应该如何处理，谢谢。

**Comment by codeskyblue** [comment]
你`adb devices`看下经常掉线吗？QQ群里@我一下

**Comment by AimHub** [comment]
same happening with me 

`PyCall::PyError (<class 'requests.exceptions.ConnectionError'>: HTTPConnectionPool(host='192.168.1.17', port=7912): Max retries exceeded with url: /jsonrpc/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1072b5d90>: Failed to establish a new connection: [Errno 61] Connection refused')))`

it just started happening today, i have not changed anything.

**Comment by codeskyblue** [comment]
atx-agent已移除
