### ISSUE TITLE
XPathSelector的方法exists调用时抛出异常："'bool' object is not callable

### ISSUE THREAD

**Issue by hipitt** [openatx/uiautomator2#674]
- pixel 3
- uiautomator2 ver: 2.12.1 

class XPathSelector(object)
    @property
    def exists(self):
        return len(self.all()) > 0

方法exists调用时抛出异常："'bool' object is not callable

**Comment by codeskyblue** [comment]
这是个属性，不能调用 在2021年04月14日 10:03，aurora 写道： 



pixel 3

uiautomator2 ver: 2.12.1



class XPathSelector(object)

@Property

def exists(self):

return len(self.all()) > 0

方法exists调用时抛出异常："'bool' object is not callable



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/openatx/uiautomator2/issues/674",

"url": "https://github.com/openatx/uiautomator2/issues/674",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by hipitt** [comment]
> 这是个属性，不能调用 在2021年04月14日 10:03，aurora 写道： pixel 3 uiautomator2 ver: 2.12.1 class XPathSelector(object) @Property def exists(self): return len(self.all()) > 0 方法exists调用时抛出异常："'bool' object is not callable —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#674", "url": "#674", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

收到
