### ISSUE TITLE
Getting error code -32001

### ISSUE THREAD

**Issue by MaleChicken5** [openatx/uiautomator2#797]
Hello team,

While using your tool, some of my devices are getting the following error and unable to acquire or connect:
```
[I 220204 10:31:13 __init__:626] [pid:24214] [192.168.2.161] restart-uiautomator since "({'code': -32001, 'message': 'java.lang.IllegalStateException', 'data': 'java.lang.IllegalStateException: UiAutomation not connected!\n\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1198)\n\tat android.app.UiAutomation.getServiceInfo(UiAutomation.java:495)\n\tat android.support.test.uiautomator.UiDevice.setCompressedLayoutHeirarchy(UiDevice.java:230)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:295)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:284)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:919)\n'}, 'dumpWindowHierarchy')" 
[D 220204 10:31:13 __init__:661] [pid:24214] [192.168.2.161] kill process(ps): uiautomator 
[D 220204 10:31:14 __init__:738] [pid:24214] [192.168.2.161] grant permissions 
[D 220204 10:31:15 __init__:683] [pid:24214] [192.168.2.161] uiautomator-v2 is starting ... left: 40.0s
```
Has anyone seen this before? Would you mind helping us on this is?

Thanks

- Android TV device
- 2.16.13

**Comment by bluepang2022** [comment]
>>> d.info
[W 220407 14:04:36 __init__:218] [pid:5364] atx-agent has something wrong, auto recovering
[D 220407 14:04:36 __init__:322] [pid:5364] [UJK0220521066836] device UJK0220521066836 is online
[I 220407 14:04:36 init:156] uiautomator2 version: 2.16.13
[D 220407 14:04:36 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 220407 14:04:36 init:295] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 220407 14:04:36 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 220407 14:04:36 init:350] Check atx-agent version
[D 220407 14:04:36 init:359] Forward: local:tcp:53942 -> remote:tcp:7912
[D 220407 14:04:37 init:359] Forward: local:tcp:53942 -> remote:tcp:7912
[D 220407 14:04:37 init:362] atx-agent version 0.10.0
[D 220407 14:04:37 init:365] device wlan ip: 172.16.2.31
[D 220407 14:04:37 __init__:661] [pid:5364] [UJK0220521066836] kill process(ps): uiautomator
[D 220407 14:04:38 __init__:682] [pid:5364] [UJK0220521066836] uiautomator-v2 is starting ... left: 40.0s
[D 220407 14:04:39 __init__:682] [pid:5364] [UJK0220521066836] uiautomator-v2 is starting ... left: 39.0s
[D 220407 14:04:40 __init__:682] [pid:5364] [UJK0220521066836] uiautomator-v2 is starting ... left: 37.9s
[I 220407 14:04:43 __init__:626] [pid:5364] [UJK0220521066836] restart-uiautomator since "({'code': -32001, 'message': 'java.lang.IllegalStateException', 'data': 'java.lang.IllegalStateException: UiAutomation not connected!\n\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1198)\n\tat android.app.UiAutomation.waitForIdle(UiAutomation.java:769)\n\tat android.support.test.uiautomator.QueryController.waitForIdle(QueryController.java:532)\n\tat android.support.test.uiautomator.QueryController.waitForIdle(QueryController.java:523)\n\tat android.support.test.uiautomator.QueryController.getCurrentPackageName(QueryController.java:511)\n\tat android.support.test.uiautomator.UiDevice.getCurrentPackageName(UiDevice.java:653)\n\tat com.github.uiautomator.stub.DeviceInfo.<init>(DeviceInfo.java:51)\n\tat com.github.uiautomator.stub.DeviceInfo.getDeviceInfo(DeviceInfo.java:44)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.deviceInfo(AutomatorServiceImpl.java:161)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:929)\n'}, 'deviceInfo')"
[D 220407 14:04:43 __init__:661] [pid:5364] [UJK0220521066836] kill process(ps): uiautomator
[D 220407 14:04:43 __init__:738] [pid:5364] [UJK0220521066836] grant permissions
[D 220407 14:04:44 __init__:682] [pid:5364] [UJK0220521066836] uiautomator-v2 is starting ... left: 40.0s
[D 220407 14:04:45 __init__:682] [pid:5364] [UJK0220521066836] uiautomator-v2 is starting ... left: 39.0s
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 487, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 556, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiAutomationNotConnectedError: ({'code': -32001, 'message': 'java.lang.IllegalStateException', 'data': 'java.lang.IllegalStateException: UiAutomation not connected!\n\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1198)\n\tat android.app.UiAutomation.waitForIdle(UiAutomation.java:769)\n\tat android.support.test.uiautomator.QueryController.waitForIdle(QueryController.java:532)\n\tat android.support.test.uiautomator.QueryController.waitForIdle(QueryController.java:523)\n\tat android.support.test.uiautomator.QueryController.getCurrentPackageName(QueryController.java:511)\n\tat android.support.test.uiautomator.UiDevice.getCurrentPackageName(UiDevice.java:653)\n\tat com.github.uiautomator.stub.DeviceInfo.<init>(DeviceInfo.java:51)\n\tat com.github.uiautomator.stub.DeviceInfo.getDeviceInfo(DeviceInfo.java:44)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.deviceInfo(AutomatorServiceImpl.java:161)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:929)\n'}, 'deviceInfo')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 449, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 480, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 489, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 651, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 651, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 618, in reset_uiautomator
    raise EnvironmentError(
OSError: [Errno Uiautomator started failed.] ({'code': -32001, 'message': 'java.lang.IllegalStateException', 'data': 'java.lang.IllegalStateException: UiAutomation not connected!\n\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1198)\n\tat android.app.UiAutomation.waitForIdle(UiAutomation.java:769)\n\tat android.support.test.uiautomator.QueryController.waitForIdle(QueryController.java:532)\n\tat android.support.test.uiautomator.QueryController.waitForIdle(QueryController.java:523)\n\tat android.support.test.uiautomator.QueryController.getCurrentPackageName(QueryController.java:511)\n\tat android.support.test.uiautomator.UiDevice.getCurrentPackageName(UiDevice.java:653)\n\tat com.github.uiautomator.stub.DeviceInfo.<init>(DeviceInfo.java:51)\n\tat com.github.uiautomator.stub.DeviceInfo.getDeviceInfo(DeviceInfo.java:44)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.deviceInfo(AutomatorServiceImpl.java:161)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:929)\n'}, 'deviceInfo'): 'https://github.com/openatx/uiautomator2/wiki/Common-issues'

**Comment by bluepang2022** [comment]
我也出现过这样的问题，华为Nova7Pro，android 10，麻烦大佬看下

**Comment by sycamore-tree-hym** [comment]
I met the same issue,and this method works for me. https://github.com/openatx/uiautomator2/wiki/Common-issues#%E6%8F%90%E7%A4%BAconnection-error
kill the atx-agent then restart it.

**Comment by codeskyblue** [comment]
新版没这个问题了

**Comment by sycamore-tree-hym** [comment]
你好，邮件已经收到，我会尽快给你回复。This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you
