### ISSUE TITLE
uiautomator2 没有更新了吗？

### ISSUE THREAD

**Issue by tianyi725** [openatx/uiautomator2#915]
uiautomator2 有api文档吗？
另外它不更新了吗？
看日期是2019年后就没了。

**Comment by codeskyblue** [comment]
更新的频率很低 ---- 回复的原邮件 ***@***.***>发送日期2023年10月08日 18:31 ***@***.***> ***@***.***>主题[openatx/uiautomator2] uiautomator2 没有更新了吗？ (Issue #915)
uiautomator2 有api文档吗？
另外它不更新了吗？
看日期是2019年后就没了。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/openatx/uiautomator2/issues/915",
"url": "https://github.com/openatx/uiautomator2/issues/915",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by codeskyblue** [comment]
开始更新了，我先关掉了。等我不更新了，你再reopen
